# SNF Analysis

In [1]:
# add install necessities in requirements.txt file
import pandas as pd
import numpy as np
import snf
from snf import datasets

#### Load all datasets needed

In [13]:
df_conners = pd.read_csv('Data/df_connors', index_col=[0])
df_behavioral = pd.read_csv('Data/df_behavioral', index_col=[0])
df_eeg = pd.read_csv('Data/df_eeg', index_col=[0])
df_labels = pd.read_csv('Data/labels', index_col=[0])
print(df_conners.dtypes)
df_eeg

id          int64
Gender      int64
cIM       float64
cHR       float64
cIE       float64
cSC       float64
dtype: object


id  Gender  adhdtype brain_oscillation electrode  fft_abs_power
0       1       1         2             Delta       FP1      15.376173
54      1       1         2             Delta        F7       7.968847
53      1       1         2              Beta       FP2      13.148877
52      1       1         2              Beta        T6       4.664137
51      1       1         2              Beta        P4       6.975211
...   ...     ...       ...               ...       ...            ...
5798  702       1         1             Delta        Fz      20.934284
5797  702       1         1             Delta        F3      17.471239
5796  702       1         1             Delta        F7      11.253618
5803  702       1         1             Delta        Cz      23.281091
5851  702       1         1             Alpha        O1      26.996481

[7296 rows x 6 columns]

### For labels

drop duplicates of ids, select only column adhdtype and create array

In [17]:
labels = df_labels.drop_duplicates()['adhdtype'].values

In [18]:
labels.shape

(96,)

### data wrangling for SNF

In order to transform all 3 dfs in three arrays of equivalent sjape, we need to reorganize data

In [19]:
df_eeg['oscil_electro'] = df_eeg['brain_oscillation'] + df_eeg['electrode']

Select only rows of interest

In [20]:
df_eeg = df_eeg[['id','adhdtype', 'oscil_electro', 'fft_abs_power']]# à enlever je crois
print(df_eeg.head())
print(df_eeg.shape)

    id  adhdtype oscil_electro  fft_abs_power
0    1         2      DeltaFP1      15.376173
54   1         2       DeltaF7       7.968847
53   1         2       BetaFP2      13.148877
52   1         2        BetaT6       4.664137
51   1         2        BetaP4       6.975211
(7296, 4)


In [21]:

df_eeg = pd.pivot_table(df_eeg, index=['id'], columns = ['oscil_electro'], values='fft_abs_power')

In [22]:
df_eeg.shape

(96, 76)

Transform in wide format in order to bet set for arrays creation

#### Remove index from behavioral and conners dataframes

In [23]:
df_behavioral = df_behavioral.set_index('id') 
df_conners = df_conners.set_index('id')

#### Transform dframes into arrays

In [24]:
conners = df_conners.to_numpy()
behavioral = df_behavioral.to_numpy()
eeg = df_eeg.to_numpy()

## combine arrays

In [26]:
data = [eeg, behavioral, conners]

In [27]:
data

[array([[10.818137, 11.69305 , 11.946326, ...,  1.548818,  2.636544,
          1.892691],
        [ 8.078669,  6.853959,  9.794557, ...,  3.068287,  6.241039,
          4.537657],
        [23.285679, 16.892647, 23.073619, ...,  5.587429, 10.264923,
         12.03943 ],
        ...,
        [ 5.026148,  5.85006 ,  5.16325 , ...,  4.025981,  4.812219,
          7.115114],
        [39.877166, 30.384745, 52.763258, ...,  8.392572, 34.811888,
         26.432725],
        [22.374774, 23.104064, 21.272516, ...,  4.340919,  7.637788,
          7.569101]]),
 array([[  1.,  90.,  91., ...,  94.,  80., 110.],
        [  1.,  90.,  91., ...,  94.,  80., 110.],
        [  1.,  90.,  91., ...,  94.,  80., 110.],
        ...,
        [  1.,  91.,  88., ...,  94.,  87., 104.],
        [  1.,  91.,  88., ...,  94.,  87., 104.],
        [  1.,  91.,  88., ...,  94.,  87., 104.]]),
 array([[ 1., 17., 31., 29.,  9.],
        [ 1., 17., 31., 29.,  9.],
        [ 1., 17., 31., 29.,  9.],
        ...,
      

In [28]:
snf_entry = {"data":data, "labels":labels}

In [30]:
snf_entry

{'data': [array([[10.818137, 11.69305 , 11.946326, ...,  1.548818,  2.636544,
           1.892691],
         [ 8.078669,  6.853959,  9.794557, ...,  3.068287,  6.241039,
           4.537657],
         [23.285679, 16.892647, 23.073619, ...,  5.587429, 10.264923,
          12.03943 ],
         ...,
         [ 5.026148,  5.85006 ,  5.16325 , ...,  4.025981,  4.812219,
           7.115114],
         [39.877166, 30.384745, 52.763258, ...,  8.392572, 34.811888,
          26.432725],
         [22.374774, 23.104064, 21.272516, ...,  4.340919,  7.637788,
           7.569101]]),
  array([[  1.,  90.,  91., ...,  94.,  80., 110.],
         [  1.,  90.,  91., ...,  94.,  80., 110.],
         [  1.,  90.,  91., ...,  94.,  80., 110.],
         ...,
         [  1.,  91.,  88., ...,  94.,  87., 104.],
         [  1.,  91.,  88., ...,  94.,  87., 104.],
         [  1.,  91.,  88., ...,  94.,  87., 104.]]),
  array([[ 1., 17., 31., 29.,  9.],
         [ 1., 17., 31., 29.,  9.],
         [ 1., 17., 31.,

### SNF analysis

In [29]:
affinity_networks = snf.make_affinity(, metric='euclidean', K=20, mu=0.5)

ValueError: Expected 2D array, got scalar array instead:
array={'data': [array([[10.818137, 11.69305 , 11.946326, ...,  1.548818,  2.636544,
         1.892691],
       [ 8.078669,  6.853959,  9.794557, ...,  3.068287,  6.241039,
         4.537657],
       [23.285679, 16.892647, 23.073619, ...,  5.587429, 10.264923,
        12.03943 ],
       ...,
       [ 5.026148,  5.85006 ,  5.16325 , ...,  4.025981,  4.812219,
         7.115114],
       [39.877166, 30.384745, 52.763258, ...,  8.392572, 34.811888,
        26.432725],
       [22.374774, 23.104064, 21.272516, ...,  4.340919,  7.637788,
         7.569101]]), array([[  1.,  90.,  91., ...,  94.,  80., 110.],
       [  1.,  90.,  91., ...,  94.,  80., 110.],
       [  1.,  90.,  91., ...,  94.,  80., 110.],
       ...,
       [  1.,  91.,  88., ...,  94.,  87., 104.],
       [  1.,  91.,  88., ...,  94.,  87., 104.],
       [  1.,  91.,  88., ...,  94.,  87., 104.]]), array([[ 1., 17., 31., 29.,  9.],
       [ 1., 17., 31., 29.,  9.],
       [ 1., 17., 31., 29.,  9.],
       ...,
       [ 1., 17., 14., 10.,  9.],
       [ 1., 17., 14., 10.,  9.],
       [ 1., 17., 14., 10.,  9.]])], 'labels': array([2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1,
       2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 1, 2, 1, 2, 1, 1,
       2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 1])}.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [21]:
fused_network = snf.snf(affinity_networks, K=20)

In [22]:
best, second = snf.get_n_clusters(fused_network)
